# Generated by Django 3.2.2 on 2021-05-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
